apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dzoe
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-dzoe@sha256:f21e2ef30fa6d3db1d2fc3f282df47d4c61f076696026d52bcf1af0cfcabb544
        name: my-nodejs
        resources: {}
status: {}
